# Generated by Django 5.2 on 2025-04-22 15:41

import articles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the article title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly slug generated from the title.', max_length=250, null=True, unique=True)),
                ('content', models.TextField(help_text='Enter the article content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the article was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the article was last updated')),
                ('picture', models.ImageField(blank=True, help_text='Optional picture for the article.', null=True, upload_to=articles.models.article_picture_upload_path, verbose_name='Article Picture')),
                ('author', models.ForeignKey(help_text='Select the author of the article', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
