# Generated by Django 5.2 on 2025-04-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('review', 'Under Review')], db_index=True, default='draft', help_text='The publication status of the article.', max_length=20),
        ),
    ]
